apiVersion: v1
kind: Service
metadata:
  name: fiber-app-service
spec:
  type: LoadBalancer  # DigitalOcean will provision a load balancer with this type
  selector:
    app: fiber-app
  ports:
  - protocol: TCP
    port: 80             # Port exposed externally
    targetPort: 8080      # Port inside the container
